services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB={DATABASE_NAME}'
      - 'POSTGRES_PASSWORD={DATABASE_PASSWORD}'
      - 'POSTGRES_USER={DATABASE_USERNAME}'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
