{
 "title": "Logs Monitoring",
 "tags": [
  "area",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"area-backend\"}"
    }
   ]
  },
  {
   "title": "Postgres Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=\"area-postgres\"}"
    }
   ]
  },
  {
   "title": "Redis Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=\"area-redis\"}"
    }
   ]
  }
 ]
}